format_version: 10
pipelines:
  Certs:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-6df4a8f:
        git: https://github.com/bdagdeviren/hcase.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            Dockerbuild:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - build
                      - -t
                      - certs
                      - .
                    command: docker
                    run_if: passed