apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.3.1
  name: cert-service
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 90s
      port: metrics
      path: /metrics
      scheme: http
  jobLabel: cert-service
  selector:
    matchLabels:
      app: certs-deployment
  namespaceSelector:
    matchNames:
      - default
